# https://github.com/torstenwalter/openshift-nginx/blob/master/tests/boilerplate-template.yml
apiVersion: v1
kind: Template
metadata:
  name: boilerplate-template
  annotations:
    description: "A boilerplate template which creates a DeploymentConfig, Service and Route for a given docker image"
    tags: "webserver"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - image: ${DOCKER_IMAGE}
          imagePullPolicy: Always
          name: application
          ports:
          - containerPort: "${{CONTAINER_PORT}}"
            protocol: TCP
          terminationMessagePath: /dev/termination-log
    triggers: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - port: "${{CONTAINER_PORT}}"
      protocol: TCP
      targetPort: "${{CONTAINER_PORT}}"
      name: http
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    port:
      targetPort: "${{CONTAINER_PORT}}"
    to:
      kind: Service
      name: ${NAME}
    tls:
      termination: edge
parameters:
- name: NAME
  description: The name for the deployment config, service and route
  required: true
- name: DOCKER_IMAGE
  description:
  required: true
- name: CONTAINER_PORT
  description: The port which will be exposed as service and route
  value: "8080"

